### ISSUE TITLE
text background not aligned with text

### ISSUE THREAD

**Issue by 2pl** [sverweij/atom-mscgen-preview#20]
Hi,

I'm using mscgen-preview 1.12.3 in Atom 1.21.0 on macOS 10.13.1
I noticed an issue with text background being not correctly aligned.

msc below:
```
msc {
  hscale="1";

  Alice [label="Alice" ],
  Bob [label="Bob" ];

  Alice => Bob [label="Background not centered", textbgcolor=lime];
}
```
Is showing as:
![bug](https://user-images.githubusercontent.com/529724/32416716-fa3655c6-c24d-11e7-9602-9a1702ca3fda.png)

**Comment by sverweij** [comment]
Hi @2pl thanks for raising this. 

- The issue occurs when there's > 1 editor instance involved (e.g. on two tab pages at the same time or consecutively; open an editor - open preview; close both, and do the same again). 
- I've also identified the root cause - but not a solution yet.

**Comment by sverweij** [comment]
@pl solution found & implemented - if the ci is done validating I'll publish 1.12.4 on atom.io

**Comment by sverweij** [comment]
@2pl 1.12.4 is on atom.io - let me know if this fixes the issue on your end as well

**Comment by 2pl** [comment]
Hi @sverweij that was a fast !
1.12.4 works great for me, background are now perfectly aligned.
Thank you.
